#!/usr/bin/env node
// Generates a VAPID keypair for Web Push and writes it to .env if absent.
import fs from "node:fs";
import path from "node:path";
import webpush from "web-push";

const ENV_PATH = path.resolve(".env");

const raw = fs.readFileSync(ENV_PATH, "utf8");
if (raw.includes("VAPID_PRIVATE_KEY=") && /VAPID_PRIVATE_KEY=\S/.test(raw)) {
  console.log("VAPID keys already present in .env — nothing to do.");
  process.exit(0);
}

const { publicKey, privateKey } = webpush.generateVAPIDKeys();

const block = `
# Web Push VAPID keys (generated by scripts/setup-vapid.mjs)
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${publicKey}
VAPID_PRIVATE_KEY=${privateKey}
VAPID_SUBJECT=mailto:hendrygaire@gmail.com
`;

fs.appendFileSync(ENV_PATH, block);
console.log("Wrote VAPID keys to .env");
